### ISSUE TITLE
# 8월 3주차 ToDo 정리

### ISSUE THREAD

**Issue by 7inug1** [7inug1/jurie_tutoring_log#42]
- [ ] 2주차 피드백 정리 및 적용
- [ ] 3주차 모바일 페이지 제작
- 모듈화
- 제작
- [ ] 3주차 fanty 데스크탑 및 모바일 페이지 제작
