### ISSUE TITLE
#  10월 4주차 To Do 및 질문

### ISSUE THREAD

**Issue by 7inug1** [7inug1/jurie_tutoring_log#90]
# WORK
- [ ] IR 기법 적용해보기
- opacity: 0; z-index: 1; width & height;
- overflow: hidden; height: XXpx; line-height: 999px;
- [ ] Owl Carousel 2: 1개로 안될 때 2개로 하기
- [ ] 보안 중요하면 iframe 쓰지 말기. 

# TODO
## 펜션 소셜 커머스
- [ ] 전체
- [ ] if/else 코드 업데이트

# 질문
- body가 전체 height 갖지 못하는 점
- http://active-themes.com/ace/demo/html/dashboard.html
- .notification 숫자 위해 after 안쓰는 게 나은지
